export interface ServiceData {
  slug: string;
  title: string;
  shortDescription: string;
  overview: string;
  features: string[];
  benefits: string[];
  technologies: string[];
  process: { step: string; description: string }[];
  businessValue: string[];
  industries: string[];
  faqs: { question: string; answer: string }[];
  icon: string;
  category: 'development' | 'cloud' | 'data' | 'security' | 'consulting' | 'design';
}

const baseProcess = [
  { step: 'Discovery', description: 'Deep-dive into business objectives, stakeholders, and technical landscape.' },
  { step: 'Strategy', description: 'Architect solutions aligned with enterprise goals and compliance requirements.' },
  { step: 'Execution', description: 'Agile delivery with transparent milestones and continuous stakeholder alignment.' },
  { step: 'Optimization', description: 'Performance tuning, knowledge transfer, and long-term support planning.' },
];

function createService(
  slug: string,
  title: string,
  shortDescription: string,
  overview: string,
  features: string[],
  benefits: string[],
  technologies: string[],
  businessValue: string[],
  industries: string[],
  faqs: { question: string; answer: string }[],
  icon: string,
  category: ServiceData['category'],
): ServiceData {
  return {
    slug,
    title,
    shortDescription,
    overview,
    features,
    benefits,
    technologies,
    process: baseProcess,
    businessValue,
    industries,
    faqs,
    icon,
    category,
  };
}

export const services: ServiceData[] = [
  createService(
    'custom-software-development',
    'Custom Software Development',
    'Bespoke enterprise applications engineered for scale, security, and long-term maintainability.',
    'Ashvill designs and builds custom software solutions tailored to your unique enterprise workflows. From complex business logic to mission-critical platforms, we deliver software that drives measurable outcomes.',
    ['Enterprise-grade architecture', 'Microservices & monolith strategies', 'Legacy system integration', 'Scalable cloud-native design', 'Comprehensive documentation', 'CI/CD pipeline integration'],
    ['Perfect fit for unique business processes', 'Full ownership of intellectual property', 'Reduced long-term licensing costs', 'Competitive differentiation', 'Seamless ecosystem integration'],
    ['TypeScript', 'Java', 'Python', '.NET', 'Node.js', 'PostgreSQL', 'Redis', 'Kubernetes'],
    ['Accelerated time-to-market for proprietary solutions', 'Operational efficiency through automation', 'Data-driven decision making infrastructure', 'Future-proof technology investments'],
    ['Finance', 'Healthcare', 'Manufacturing', 'Retail', 'Logistics', 'Energy'],
    [
      { question: 'How long does custom software development take?', answer: 'Timelines vary based on scope. MVPs typically take 3–6 months; enterprise platforms may require 6–18 months. We provide detailed estimates after discovery.' },
      { question: 'Do we own the source code?', answer: 'Yes. Clients retain full intellectual property rights upon project completion and final payment.' },
    ],
    'Code2',
    'development',
  ),
  createService(
    'web-development',
    'Web Development',
    'High-performance web applications and portals built with modern frameworks and enterprise standards.',
    'We craft responsive, accessible, and blazing-fast web experiences that convert visitors into enterprise clients. Our web solutions prioritize performance, security, and exceptional user experience.',
    ['Progressive Web Apps', 'Single Page Applications', 'Server-side rendering', 'Headless CMS integration', 'E-commerce platforms', 'Enterprise portals'],
    ['Superior user engagement', 'Cross-platform compatibility', 'SEO-optimized architecture', 'Reduced bounce rates', 'Enhanced brand credibility'],
    ['Next.js', 'React', 'Vue.js', 'Tailwind CSS', 'GraphQL', 'REST APIs', 'Vercel', 'AWS'],
    ['Increased digital presence and lead generation', 'Streamlined customer self-service', 'Reduced operational overhead', 'Global accessibility 24/7'],
    ['E-commerce', 'SaaS', 'Education', 'Government', 'Media', 'Real Estate'],
    [
      { question: 'What web technologies do you recommend?', answer: 'We recommend based on your requirements. Next.js with React is our default for enterprise applications requiring SEO and performance.' },
      { question: 'Do you provide ongoing maintenance?', answer: 'Yes. We offer application maintenance packages including security updates, performance monitoring, and feature enhancements.' },
    ],
    'Globe',
    'development',
  ),
  createService(
    'mobile-apps',
    'Mobile App Development',
    'Native and cross-platform mobile applications that deliver premium experiences on iOS and Android.',
    'Ashvill builds mobile applications that enterprise users love — intuitive interfaces, offline capabilities, and enterprise-grade security baked in from day one.',
    ['iOS & Android native development', 'React Native & Flutter', 'Offline-first architecture', 'Push notifications', 'Biometric authentication', 'App Store optimization'],
    ['Expanded customer reach', 'Enhanced user loyalty', 'Real-time engagement', 'Mobile workforce enablement', 'Competitive mobile presence'],
    ['Swift', 'Kotlin', 'React Native', 'Flutter', 'Firebase', 'GraphQL', 'AWS Amplify'],
    ['New revenue channels through mobile commerce', 'Improved field team productivity', 'Real-time data collection and analytics', 'Brand presence in app stores'],
    ['Healthcare', 'Fintech', 'Retail', 'Transportation', 'Hospitality', 'Field Services'],
    [
      { question: 'Native or cross-platform?', answer: 'Cross-platform (React Native/Flutter) suits most enterprise needs. Native is recommended for performance-critical or hardware-intensive applications.' },
      { question: 'Do you handle app store submissions?', answer: 'Yes. We manage the complete submission process for both Apple App Store and Google Play Store.' },
    ],
    'Smartphone',
    'development',
  ),
  createService(
    'cloud',
    'Cloud Solutions',
    'Strategic cloud architecture, migration, and management across AWS, Azure, and Google Cloud.',
    'Transform your infrastructure with cloud-native solutions designed for resilience, scalability, and cost optimization. We architect multi-cloud and hybrid environments tailored to enterprise compliance needs.',
    ['Cloud architecture design', 'Infrastructure as Code', 'Auto-scaling configurations', 'Disaster recovery planning', 'Cost optimization', 'Multi-cloud strategies'],
    ['Reduced infrastructure costs', 'Infinite scalability', '99.99% uptime targets', 'Global deployment capability', 'Pay-as-you-grow economics'],
    ['AWS', 'Azure', 'Google Cloud', 'Terraform', 'CloudFormation', 'Docker', 'Kubernetes'],
    ['40–60% infrastructure cost reduction', 'Faster deployment cycles', 'Enhanced disaster recovery', 'Global market expansion capability'],
    ['Finance', 'Healthcare', 'E-commerce', 'Media', 'Government', 'Startups'],
    [
      { question: 'Which cloud provider do you recommend?', answer: 'AWS is our primary expertise, but we are certified across AWS, Azure, and GCP. We recommend based on your existing ecosystem and compliance requirements.' },
      { question: 'Can you manage our existing cloud infrastructure?', answer: 'Yes. We offer managed cloud services including monitoring, optimization, security patching, and 24/7 incident response.' },
    ],
    'Cloud',
    'cloud',
  ),
  createService(
    'devops',
    'DevOps & CI/CD',
    'Accelerate delivery with automated pipelines, infrastructure automation, and Site Reliability Engineering practices.',
    'Our DevOps practice bridges development and operations, enabling your teams to ship faster, more reliably, and with confidence through modern CI/CD and SRE methodologies.',
    ['CI/CD pipeline design', 'Container orchestration', 'Infrastructure automation', 'Monitoring & alerting', 'GitOps workflows', 'SRE implementation'],
    ['10x faster deployment frequency', 'Reduced failure rates', 'Automated quality gates', 'Improved team collaboration', 'Faster incident recovery'],
    ['GitHub Actions', 'GitLab CI', 'Jenkins', 'ArgoCD', 'Prometheus', 'Grafana', 'ELK Stack'],
    ['Dramatically reduced time-to-market', 'Lower operational risk', 'Improved developer productivity', 'Predictable release cycles'],
    ['SaaS', 'Fintech', 'E-commerce', 'Technology', 'Telecommunications', 'Gaming'],
    [
      { question: 'How quickly can you set up CI/CD?', answer: 'Basic pipelines can be operational within 2–4 weeks. Enterprise-grade pipelines with full testing, security scanning, and deployment automation typically take 6–8 weeks.' },
      { question: 'Do you provide DevOps training?', answer: 'Yes. We offer team training and knowledge transfer as part of every DevOps engagement.' },
    ],
    'GitBranch',
    'cloud',
  ),
  createService(
    'cybersecurity',
    'Cybersecurity',
    'Comprehensive security assessments, implementation, and managed security services for enterprise protection.',
    'Protect your digital assets with enterprise-grade cybersecurity solutions. From penetration testing to SOC implementation, Ashvill safeguards your organization against evolving threats.',
    ['Security audits & assessments', 'Penetration testing', 'SOC implementation', 'Identity & access management', 'Compliance frameworks', 'Incident response planning'],
    ['Reduced breach risk', 'Regulatory compliance', 'Customer trust enhancement', 'Proactive threat detection', 'Business continuity assurance'],
    ['OWASP', 'NIST', 'ISO 27001', 'SOC 2', 'SIEM', 'WAF', 'Zero Trust'],
    ['Protection of critical business assets', 'Compliance with industry regulations', 'Reduced financial risk from breaches', 'Enhanced customer and partner confidence'],
    ['Finance', 'Healthcare', 'Government', 'Defense', 'Insurance', 'Legal'],
    [
      { question: 'What compliance frameworks do you support?', answer: 'We support SOC 2, ISO 27001, HIPAA, PCI DSS, GDPR, and industry-specific frameworks.' },
      { question: 'Do you offer 24/7 security monitoring?', answer: 'Yes. Our managed security services include 24/7 SOC monitoring, threat intelligence, and incident response.' },
    ],
    'Shield',
    'security',
  ),
  createService(
    'ai',
    'AI & Machine Learning',
    'Intelligent systems that automate decisions, predict outcomes, and unlock insights from your data.',
    'Leverage artificial intelligence and machine learning to transform raw data into strategic advantage. We build production-ready AI systems that integrate seamlessly with your enterprise workflows.',
    ['Predictive analytics', 'Computer vision', 'Natural language processing', 'Recommendation engines', 'Anomaly detection', 'MLOps pipelines'],
    ['Automated decision-making', 'Predictive business insights', 'Process automation at scale', 'Competitive AI advantage', 'Data monetization'],
    ['Python', 'TensorFlow', 'PyTorch', 'scikit-learn', 'MLflow', 'Kubeflow', 'AWS SageMaker'],
    ['Revenue growth through intelligent automation', 'Cost reduction via predictive maintenance', 'Enhanced customer personalization', 'New AI-powered product capabilities'],
    ['Finance', 'Healthcare', 'Retail', 'Manufacturing', 'Insurance', 'Telecommunications'],
    [
      { question: 'Do we need large datasets to start?', answer: 'Not always. We can begin with available data and implement transfer learning or synthetic data strategies. We assess data readiness during discovery.' },
      { question: 'How do you ensure AI model reliability?', answer: 'We implement MLOps practices including model versioning, A/B testing, drift detection, and continuous monitoring in production.' },
    ],
    'Brain',
    'data',
  ),
  createService(
    'generative-ai',
    'Generative AI',
    'Enterprise-grade LLM integration, RAG systems, and AI copilots that augment your workforce.',
    'Harness the power of generative AI safely and effectively. We build custom AI assistants, document processing systems, and intelligent automation powered by leading LLM technologies.',
    ['Custom LLM fine-tuning', 'RAG architecture', 'AI copilots & assistants', 'Document intelligence', 'Conversational AI', 'AI governance frameworks'],
    ['10x productivity gains', 'Intelligent content generation', 'Automated knowledge retrieval', 'Enhanced customer support', 'Innovation acceleration'],
    ['OpenAI', 'Anthropic', 'LangChain', 'Pinecone', 'Hugging Face', 'Azure OpenAI', 'AWS Bedrock'],
    ['Dramatic reduction in manual document processing', '24/7 intelligent customer support', 'Accelerated research and development', 'Competitive differentiation through AI'],
    ['Legal', 'Healthcare', 'Finance', 'Education', 'Media', 'Customer Service'],
    [
      { question: 'How do you address AI security concerns?', answer: 'We implement guardrails, content filtering, access controls, audit logging, and data isolation to ensure enterprise-safe AI deployments.' },
      { question: 'Can you integrate AI with our existing systems?', answer: 'Yes. We specialize in integrating generative AI with CRMs, ERPs, knowledge bases, and custom enterprise applications via APIs.' },
    ],
    'Sparkles',
    'data',
  ),
  createService(
    'erp',
    'ERP Solutions',
    'Enterprise resource planning implementation, customization, and integration for operational excellence.',
    'Streamline your business operations with expertly implemented ERP solutions. We customize and integrate ERP platforms to unify your finance, supply chain, HR, and operations.',
    ['ERP selection consulting', 'Implementation & customization', 'Data migration', 'Third-party integrations', 'User training', 'Post-go-live support'],
    ['Unified business processes', 'Real-time operational visibility', 'Reduced manual workflows', 'Improved compliance tracking', 'Scalable operations foundation'],
    ['SAP', 'Oracle', 'Microsoft Dynamics', 'Odoo', 'NetSuite', 'Salesforce'],
    ['30–50% reduction in operational inefficiencies', 'Single source of truth for business data', 'Improved regulatory compliance', 'Foundation for digital transformation'],
    ['Manufacturing', 'Distribution', 'Retail', 'Construction', 'Pharmaceuticals', 'Automotive'],
    [
      { question: 'How long does ERP implementation take?', answer: 'Typical implementations range from 6–18 months depending on modules, customization level, and data migration complexity.' },
      { question: 'Can you integrate ERP with existing systems?', answer: 'Yes. We specialize in ERP integration with CRMs, e-commerce platforms, BI tools, and custom applications.' },
    ],
    'Building2',
    'consulting',
  ),
  createService(
    'crm',
    'CRM Solutions',
    'Customer relationship management platforms that drive sales growth and customer retention.',
    'Build stronger customer relationships with CRM solutions tailored to your sales, marketing, and service workflows. We implement and customize leading CRM platforms for measurable revenue impact.',
    ['CRM platform selection', 'Sales pipeline automation', 'Marketing automation', 'Customer service portals', 'Analytics dashboards', 'Mobile CRM access'],
    ['Increased sales conversion', 'Improved customer retention', '360-degree customer view', 'Automated lead nurturing', 'Data-driven sales forecasting'],
    ['Salesforce', 'HubSpot', 'Microsoft Dynamics 365', 'Zoho CRM', 'Pipedrive', 'Custom CRM'],
    ['20–35% increase in sales productivity', 'Higher customer lifetime value', 'Reduced customer churn', 'Improved marketing ROI'],
    ['B2B Services', 'Real Estate', 'Insurance', 'SaaS', 'Financial Services', 'Professional Services'],
    [
      { question: 'Which CRM platform is best for us?', answer: 'We evaluate your team size, sales process, integration needs, and budget to recommend the optimal platform during our discovery phase.' },
      { question: 'Can you migrate data from our current CRM?', answer: 'Yes. We handle complete data migration including contacts, deals, activities, and custom fields with validation and deduplication.' },
    ],
    'Users',
    'consulting',
  ),
  createService(
    'saas',
    'SaaS Development',
    'End-to-end SaaS product engineering from MVP to scale-ready multi-tenant platforms.',
    'Launch and scale your SaaS product with Ashvill\'s full-stack expertise. We build multi-tenant architectures with subscription billing, analytics, and enterprise-grade security.',
    ['Multi-tenant architecture', 'Subscription billing integration', 'Admin dashboards', 'API-first design', 'Usage analytics', 'White-label capabilities'],
    ['Recurring revenue model', 'Rapid market validation', 'Scalable user onboarding', 'Global deployment readiness', 'Investor-ready product'],
    ['Next.js', 'Node.js', 'PostgreSQL', 'Stripe', 'Redis', 'AWS', 'Auth0'],
    ['New recurring revenue streams', 'Scalable business model', 'Reduced customer acquisition costs', 'Platform for ecosystem partnerships'],
    ['B2B SaaS', 'HR Tech', 'MarTech', 'FinTech', 'EdTech', 'HealthTech'],
    [
      { question: 'How quickly can you build an MVP?', answer: 'A production-quality SaaS MVP typically takes 8–14 weeks, including authentication, core features, billing, and admin panel.' },
      { question: 'Do you help with SaaS scaling?', answer: 'Yes. We architect for scale from day one and provide ongoing optimization as your user base grows.' },
    ],
    'Layers',
    'development',
  ),
  createService(
    'ui-ux',
    'UI/UX Design',
    'Human-centered design that transforms complex enterprise workflows into intuitive digital experiences.',
    'Great design drives adoption. Our UI/UX team creates research-backed, accessible interfaces that reduce training costs and accelerate user productivity across your organization.',
    ['User research & personas', 'Information architecture', 'Wireframing & prototyping', 'Design systems', 'Usability testing', 'Accessibility audits'],
    ['Higher user adoption rates', 'Reduced training costs', 'Improved task completion', 'Enhanced brand perception', 'WCAG compliance'],
    ['Figma', 'Adobe XD', 'Framer', 'Storybook', 'Maze', 'Hotjar'],
    ['Increased product adoption and ROI', 'Reduced support ticket volume', 'Competitive differentiation through design', 'Inclusive experiences for all users'],
    ['Enterprise Software', 'Healthcare', 'Finance', 'E-commerce', 'Education', 'Government'],
    [
      { question: 'Do you conduct user research?', answer: 'Yes. Every engagement includes stakeholder interviews, user research, and usability testing to ensure designs meet real user needs.' },
      { question: 'Can you create a design system?', answer: 'Yes. We build comprehensive design systems with component libraries, documentation, and developer handoff specifications.' },
    ],
    'Palette',
    'design',
  ),
  createService(
    'qa',
    'QA & Testing',
    'Comprehensive quality assurance ensuring your software meets the highest reliability standards.',
    'Ship with confidence. Our QA engineers implement rigorous testing strategies — automated, manual, performance, and security — to protect your brand and users.',
    ['Test strategy & planning', 'Automated test suites', 'Performance testing', 'Security testing', 'API testing', 'Mobile testing'],
    ['Reduced production defects', 'Faster release cycles', 'Improved user satisfaction', 'Lower maintenance costs', 'Compliance verification'],
    ['Selenium', 'Cypress', 'Playwright', 'Jest', 'JMeter', 'Postman', 'BrowserStack'],
    ['50–80% reduction in production bugs', 'Faster time-to-market with confidence', 'Protected brand reputation', 'Lower total cost of ownership'],
    ['All Industries'],
    [
      { question: 'What testing approach do you use?', answer: 'We follow a risk-based testing approach combining automated regression, exploratory testing, and performance validation tailored to your release cadence.' },
      { question: 'Can you integrate testing into our CI/CD?', answer: 'Yes. We embed automated tests directly into your CI/CD pipeline for continuous quality assurance.' },
    ],
    'TestTube',
    'development',
  ),
  createService(
    'automation',
    'Automation',
    'Intelligent process automation that eliminates manual workflows and accelerates business operations.',
    'Automate repetitive tasks, integrate disparate systems, and orchestrate complex workflows with our RPA and intelligent automation solutions.',
    ['RPA implementation', 'Workflow orchestration', 'API integrations', 'Document processing automation', 'Report generation', 'Notification systems'],
    ['60–80% reduction in manual tasks', 'Error elimination', '24/7 process execution', 'Faster processing times', 'Employee productivity gains'],
    ['UiPath', 'Power Automate', 'Zapier', 'n8n', 'Python', 'Apache Airflow'],
    ['Significant operational cost savings', 'Improved accuracy and compliance', 'Employee focus on high-value work', 'Scalable operations without headcount growth'],
    ['Finance', 'HR', 'Insurance', 'Legal', 'Healthcare', 'Supply Chain'],
    [
      { question: 'What processes can be automated?', answer: 'Data entry, report generation, invoice processing, onboarding workflows, system integrations, and any rule-based repetitive task.' },
      { question: 'How do you measure automation ROI?', answer: 'We establish baseline metrics before automation and track time saved, error reduction, and cost savings post-implementation.' },
    ],
    'Cog',
    'development',
  ),
  createService(
    'data-analytics',
    'Data Analytics',
    'Transform raw data into actionable insights with advanced analytics and visualization platforms.',
    'Make data-driven decisions with confidence. We build analytics pipelines, dashboards, and reporting systems that surface the insights your leadership team needs.',
    ['Data pipeline engineering', 'Interactive dashboards', 'Real-time analytics', 'Predictive modeling', 'Data warehouse design', 'Self-service BI tools'],
    ['Data-driven decision making', 'Real-time business visibility', 'Trend identification', 'Performance benchmarking', 'Predictive capabilities'],
    ['Python', 'SQL', 'Apache Spark', 'dbt', 'Tableau', 'Power BI', 'Looker'],
    ['Faster strategic decision-making', 'Identification of revenue opportunities', 'Operational efficiency insights', 'Competitive intelligence'],
    ['Retail', 'Finance', 'Healthcare', 'Marketing', 'Operations', 'E-commerce'],
    [
      { question: 'Can you work with our existing data sources?', answer: 'Yes. We integrate with databases, APIs, SaaS platforms, spreadsheets, and legacy systems to create unified analytics.' },
      { question: 'Do you build real-time dashboards?', answer: 'Yes. We implement both batch and real-time streaming analytics depending on your latency requirements.' },
    ],
    'BarChart3',
    'data',
  ),
  createService(
    'business-intelligence',
    'Business Intelligence',
    'Executive-grade BI platforms that unify data and empower strategic decision-making.',
    'Consolidate fragmented data into a single source of truth. Our BI solutions deliver the KPIs, reports, and visualizations your C-suite needs to steer the organization.',
    ['BI platform implementation', 'Executive dashboards', 'KPI framework design', 'Automated reporting', 'Data governance', 'Self-service analytics'],
    ['Unified data visibility', 'Automated executive reporting', 'Faster strategic decisions', 'Cross-department alignment', 'Regulatory reporting automation'],
    ['Power BI', 'Tableau', 'Looker', 'Snowflake', 'BigQuery', 'Redshift'],
    ['Executive visibility into all business metrics', 'Reduced reporting cycle times', 'Improved cross-functional alignment', 'Foundation for advanced analytics'],
    ['Finance', 'Retail', 'Manufacturing', 'Healthcare', 'Telecommunications', 'Energy'],
    [
      { question: 'How is BI different from data analytics?', answer: 'BI focuses on descriptive and diagnostic analytics (what happened and why), while data analytics extends into predictive and prescriptive insights.' },
      { question: 'Can non-technical users access dashboards?', answer: 'Yes. We design self-service BI with intuitive interfaces so business users can explore data without technical expertise.' },
    ],
    'PieChart',
    'data',
  ),
  createService(
    'api-development',
    'API Development',
    'Robust, secure, and well-documented APIs that power integrations and digital ecosystems.',
    'Build the connective tissue of your digital ecosystem. We design RESTful and GraphQL APIs with comprehensive documentation, versioning, and developer portals.',
    ['REST & GraphQL API design', 'API gateway implementation', 'Developer portals', 'Rate limiting & throttling', 'OAuth 2.0 / OIDC', 'API versioning strategies'],
    ['Seamless system integration', 'Partner ecosystem enablement', 'Mobile & web backend power', 'Microservices communication', 'Third-party connectivity'],
    ['Node.js', 'Python', 'Kong', 'AWS API Gateway', 'OpenAPI', 'GraphQL', 'gRPC'],
    ['New partnership and integration revenue', 'Faster partner onboarding', 'Platform extensibility', 'Reduced integration maintenance costs'],
    ['SaaS', 'Fintech', 'E-commerce', 'Healthcare', 'IoT', 'Logistics'],
    [
      { question: 'REST or GraphQL?', answer: 'REST suits most enterprise integrations. GraphQL is ideal when clients need flexible data fetching. We often implement both.' },
      { question: 'Do you provide API documentation?', answer: 'Yes. Every API includes OpenAPI/Swagger documentation, SDKs, and a developer portal for partner self-service.' },
    ],
    'Plug',
    'development',
  ),
  createService(
    'it-consulting',
    'IT Consulting',
    'Strategic technology advisory that aligns IT investments with business objectives.',
    'Navigate complex technology decisions with expert guidance. Our consultants bring decades of combined experience across industries to architect your digital future.',
    ['Technology assessment', 'Digital transformation roadmaps', 'Vendor selection', 'Architecture review', 'Cost optimization analysis', 'IT governance frameworks'],
    ['Informed technology investments', 'Reduced project risk', 'Accelerated digital transformation', 'Optimized IT spending', 'Competitive technology positioning'],
    ['TOGAF', 'Agile', 'ITIL', 'Cloud-native', 'Enterprise Architecture'],
    ['Maximized ROI on technology investments', 'Reduced project failure rates', 'Clear digital transformation roadmap', 'Optimized vendor relationships'],
    ['All Industries'],
    [
      { question: 'How do consulting engagements work?', answer: 'We begin with a discovery assessment, deliver a strategic roadmap with prioritized recommendations, and optionally support implementation.' },
      { question: 'Can you help with vendor selection?', answer: 'Yes. We provide objective vendor evaluation based on your requirements, budget, and long-term technology strategy.' },
    ],
    'Lightbulb',
    'consulting',
  ),
  createService(
    'staff-augmentation',
    'Staff Augmentation',
    'Elite technology talent embedded in your team to accelerate delivery without hiring overhead.',
    'Scale your development capacity instantly with pre-vetted Ashvill engineers. Our professionals integrate seamlessly with your workflows, tools, and culture.',
    ['Pre-vetted senior engineers', 'Flexible engagement models', 'Domain-specific expertise', 'Timezone-aligned teams', 'Knowledge transfer', 'Performance reporting'],
    ['Instant capacity scaling', 'No recruitment overhead', 'Specialized skill access', 'Flexible cost structure', 'Reduced time-to-hire'],
    ['Full-stack', 'Cloud', 'AI/ML', 'DevOps', 'Mobile', 'QA', 'UI/UX'],
    ['40–60% faster project delivery', 'Access to specialized skills on demand', 'Reduced hiring and onboarding costs', 'Flexibility to scale up or down'],
    ['All Industries'],
    [
      { question: 'How quickly can engineers start?', answer: 'Senior engineers can typically onboard within 1–2 weeks after requirements alignment and NDA execution.' },
      { question: 'What engagement models are available?', answer: 'Full-time dedicated, part-time, project-based, and hybrid models. Contracts are flexible with monthly terms.' },
    ],
    'UserPlus',
    'consulting',
  ),
  createService(
    'dedicated-teams',
    'Dedicated Teams',
    'Fully managed cross-functional teams that operate as an extension of your organization.',
    'Get a complete product team — developers, designers, QA, and project managers — dedicated exclusively to your initiatives with Ashvill\'s management oversight.',
    ['Cross-functional team composition', 'Dedicated project management', 'Sprint planning & delivery', 'Continuous improvement', 'Transparent reporting', 'IP protection'],
    ['Complete team without hiring', 'Consistent velocity', 'Deep domain knowledge', 'Predictable delivery', 'Full accountability'],
    ['Agile/Scrum', 'Kanban', 'Jira', 'Confluence', 'Full technology stack'],
    ['Predictable product delivery cadence', 'Deep accumulated product knowledge', 'Significant cost savings vs. in-house hiring', 'Focus on core business while we build'],
    ['SaaS', 'Enterprise', 'Startups', 'Digital Agencies', 'Corporations'],
    [
      { question: 'How is this different from staff augmentation?', answer: 'Dedicated teams are fully managed by Ashvill with defined deliverables, while staff augmentation places individual engineers under your direct management.' },
      { question: 'What team sizes are available?', answer: 'Teams typically range from 3–15 members depending on project scope. We scale teams as your needs evolve.' },
    ],
    'UsersRound',
    'consulting',
  ),
  createService(
    'legacy-modernization',
    'Legacy Modernization',
    'Transform aging systems into modern, cloud-native architectures without business disruption.',
    'Modernize legacy applications strategically with minimal risk. We assess, plan, and execute migrations that preserve business logic while unlocking modern capabilities.',
    ['Legacy system assessment', 'Strangler fig migration', 'Cloud re-platforming', 'Database modernization', 'API extraction', 'Parallel run strategies'],
    ['Reduced maintenance costs', 'Improved system performance', 'Enhanced security posture', 'Cloud readiness', 'Developer productivity gains'],
    ['Microservices', 'Containers', 'Cloud-native', 'Event-driven', 'Modern frameworks'],
    ['50–70% reduction in maintenance costs', 'Improved system performance and reliability', 'Enhanced security and compliance', 'Foundation for innovation'],
    ['Banking', 'Insurance', 'Government', 'Manufacturing', 'Telecommunications', 'Utilities'],
    [
      { question: 'How do you minimize migration risk?', answer: 'We use incremental migration strategies (strangler fig pattern) allowing parallel operation of legacy and modern systems during transition.' },
      { question: 'Can you modernize without downtime?', answer: 'Yes. Our migration strategies are designed for zero-downtime transitions with rollback capabilities at every stage.' },
    ],
    'RefreshCw',
    'development',
  ),
  createService(
    'application-maintenance',
    'Application Maintenance',
    'Proactive maintenance and support that keeps your applications secure, performant, and evolving.',
    'Protect your technology investments with comprehensive application maintenance. We handle updates, monitoring, bug fixes, and enhancements so your team can focus on growth.',
    ['24/7 monitoring & alerting', 'Security patch management', 'Performance optimization', 'Bug fixes & enhancements', 'SLA-backed support', 'Technical debt reduction'],
    ['Maximum uptime', 'Proactive issue resolution', 'Continuous security', 'Predictable support costs', 'Extended application lifespan'],
    ['Monitoring tools', 'CI/CD', 'Cloud platforms', 'All major frameworks'],
    ['99.9%+ application uptime', 'Reduced security vulnerability exposure', 'Predictable monthly support costs', 'Continuous performance improvement'],
    ['All Industries'],
    [
      { question: 'What SLAs do you offer?', answer: 'We offer tiered SLAs from 8x5 business hours to 24x7 with response times ranging from 4 hours to 30 minutes for critical issues.' },
      { question: 'Can you maintain applications you didn\'t build?', answer: 'Yes. We perform codebase assessments and onboard existing applications into our maintenance framework.' },
    ],
    'Wrench',
    'development',
  ),
  createService(
    'cloud-migration',
    'Cloud Migration',
    'Seamless migration of workloads, databases, and applications to cloud infrastructure.',
    'Move to the cloud with confidence. Our proven migration methodology ensures minimal disruption while optimizing for performance, cost, and security in your target cloud environment.',
    ['Migration assessment', 'Workload prioritization', 'Database migration', 'Application re-platforming', 'Network architecture', 'Post-migration optimization'],
    ['Reduced infrastructure costs', 'Improved scalability', 'Enhanced disaster recovery', 'Global reach', 'Reduced data center dependency'],
    ['AWS Migration Hub', 'Azure Migrate', 'Database Migration Service', 'Terraform', 'CloudEndure'],
    ['30–50% infrastructure cost reduction', 'Improved disaster recovery capabilities', 'Global scalability for business expansion', 'Reduced capital expenditure'],
    ['Finance', 'Healthcare', 'Retail', 'Manufacturing', 'Media', 'Education'],
    [
      { question: 'How long does cloud migration take?', answer: 'Timeline depends on complexity. A phased migration of 10–20 workloads typically takes 3–6 months. We provide detailed timelines after assessment.' },
      { question: 'What migration strategies do you use?', answer: 'Rehost (lift-and-shift), replatform, refactor, and hybrid approaches — selected based on each workload\'s characteristics and business priorities.' },
    ],
    'ArrowRightLeft',
    'cloud',
  ),
];

export function getServiceBySlug(slug: string): ServiceData | undefined {
  return services.find((s) => s.slug === slug);
}

export function getServicesByCategory(category: ServiceData['category']): ServiceData[] {
  return services.filter((s) => s.category === category);
}

export const serviceCategories = [
  { id: 'development' as const, label: 'Development', description: 'Custom software, web, mobile, and SaaS solutions' },
  { id: 'cloud' as const, label: 'Cloud & DevOps', description: 'Cloud architecture, migration, and CI/CD pipelines' },
  { id: 'data' as const, label: 'Data & AI', description: 'Analytics, BI, machine learning, and generative AI' },
  { id: 'security' as const, label: 'Security', description: 'Cybersecurity assessments and managed protection' },
  { id: 'consulting' as const, label: 'Consulting', description: 'IT strategy, ERP, CRM, and team augmentation' },
  { id: 'design' as const, label: 'Design', description: 'UI/UX design systems and user research' },
];
